//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderBook_Project.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderBook_Project.Resources.ViewText", typeof(ViewText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All products.
        /// </summary>
        public static string ALL_PRODUCTS {
            get {
                return ResourceManager.GetString("ALL_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string BUTTON_ADD_TO_CART {
            get {
                return ResourceManager.GetString("BUTTON_ADD_TO_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart confirmation.
        /// </summary>
        public static string BUTTON_CART_CONFIRM {
            get {
                return ResourceManager.GetString("BUTTON_CART_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Button_Change {
            get {
                return ResourceManager.GetString("Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BUTTON_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed order.
        /// </summary>
        public static string Button_Proceed_Order {
            get {
                return ResourceManager.GetString("Button_Proceed_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BUTTON_SEARCH {
            get {
                return ResourceManager.GetString("BUTTON_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string BUTTON_SUBMIT {
            get {
                return ResourceManager.GetString("BUTTON_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to track orders, save a list of favorite products, receive many attractive deals..
        /// </summary>
        public static string Decription_login {
            get {
                return ResourceManager.GetString("Decription_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAM.
        /// </summary>
        public static string DV_GAM {
            get {
                return ResourceManager.GetString("DV_GAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string DV_SO_TRANG {
            get {
                return ResourceManager.GetString("DV_SO_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00x00x00.
        /// </summary>
        public static string EXAM_KICH_THUOC {
            get {
                return ResourceManager.GetString("EXAM_KICH_THUOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string Exist_Email {
            get {
                return ResourceManager.GetString("Exist_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string Export_to_Excel {
            get {
                return ResourceManager.GetString("Export_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password? Click .
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID Orders.
        /// </summary>
        public static string Id_Orders {
            get {
                return ResourceManager.GetString("Id_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In transit.
        /// </summary>
        public static string In_Transit {
            get {
                return ResourceManager.GetString("In_Transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the verification code.
        /// </summary>
        public static string Input_Code {
            get {
                return ResourceManager.GetString("Input_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string LABLE_HELLO {
            get {
                return ResourceManager.GetString("LABLE_HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LABLE_LOGIN {
            get {
                return ResourceManager.GetString("LABLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string LABLE_OR {
            get {
                return ResourceManager.GetString("LABLE_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LABLE_REGISTER {
            get {
                return ResourceManager.GetString("LABLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string LABLE_SEARCH {
            get {
                return ResourceManager.GetString("LABLE_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information.
        /// </summary>
        public static string LINK_UPDATE_INFO {
            get {
                return ResourceManager.GetString("LINK_UPDATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Login_name {
            get {
                return ResourceManager.GetString("Login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Images failed.
        /// </summary>
        public static string Message_Add_Image_Failed {
            get {
                return ResourceManager.GetString("Message_Add_Image_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product failed.
        /// </summary>
        public static string Message_Add_Product_Failed {
            get {
                return ResourceManager.GetString("Message_Add_Product_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product successfully.
        /// </summary>
        public static string Message_Add_Product_Success {
            get {
                return ResourceManager.GetString("Message_Add_Product_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password incorrectly.
        /// </summary>
        public static string Message_Confim_Password {
            get {
                return ResourceManager.GetString("Message_Confim_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email format.
        /// </summary>
        public static string Message_Confirm_Email {
            get {
                return ResourceManager.GetString("Message_Confirm_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect file format.
        /// </summary>
        public static string Message_Incorrect_File_Format {
            get {
                return ResourceManager.GetString("Message_Incorrect_File_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of 20 characters.
        /// </summary>
        public static string Message_Max_Length {
            get {
                return ResourceManager.GetString("Message_Max_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum of 6 characters.
        /// </summary>
        public static string Message_Min_Length {
            get {
                return ResourceManager.GetString("Message_Min_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order was successful.
        /// </summary>
        public static string Message_order_success {
            get {
                return ResourceManager.GetString("Message_order_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Message_Required {
            get {
                return ResourceManager.GetString("Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not updated order information.
        /// </summary>
        public static string Message_update_infor_order {
            get {
                return ResourceManager.GetString("Message_update_infor_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update product failed.
        /// </summary>
        public static string Message_Update_Product_Failed {
            get {
                return ResourceManager.GetString("Message_Update_Product_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update product success.
        /// </summary>
        public static string Message_Update_Product_Success {
            get {
                return ResourceManager.GetString("Message_Update_Product_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format .jpeg, .jpg, .png. File size max 5MB. .
        /// </summary>
        public static string NOTE_UPLOAD_FILE_IMAGE {
            get {
                return ResourceManager.GetString("NOTE_UPLOAD_FILE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included VAT (if any).
        /// </summary>
        public static string NOTE_VAT {
            get {
                return ResourceManager.GetString("NOTE_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code is incorrect.
        /// </summary>
        public static string Notification_Code {
            get {
                return ResourceManager.GetString("Notification_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +84 353 033 933.
        /// </summary>
        public static string PHONE_CONTACT {
            get {
                return ResourceManager.GetString("PHONE_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input address.
        /// </summary>
        public static string PLACEHOLDER_INPUT_ADDRESS {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password again.
        /// </summary>
        public static string PLACEHOLDER_INPUT_COMFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_COMFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string PLACEHOLDER_INPUT_EMAIL {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        public static string PLACEHOLDER_INPUT_MOBILE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        public static string PLACEHOLDER_INPUT_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string PLACEHOLDER_INPUT_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password.
        /// </summary>
        public static string PLACEHOLDER_INPUT_PASSWORD_NEW {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_PASSWORD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        public static string PLACEHOLDER_INPUT_USERNAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_INPUT_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string PLACEHOLDER_USERNAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price current.
        /// </summary>
        public static string price_current {
            get {
                return ResourceManager.GetString("price_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete employee.
        /// </summary>
        public static string Question_Delete_Employee {
            get {
                return ResourceManager.GetString("Question_Delete_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t stop giving love even if you don’t receive it! Smile and have patience!.
        /// </summary>
        public static string RANDOM_TEXT_0 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All work and no play makes Jack a dull boy..
        /// </summary>
        public static string RANDOM_TEXT_1 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A great lover is not one who loves many, but one who loves one woman for life..
        /// </summary>
        public static string RANDOM_TEXT_2 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendship often ends in love, but love in friendship – never..
        /// </summary>
        public static string RANDOM_TEXT_3 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clean fast is better than a dirty breakfast..
        /// </summary>
        public static string RANDOM_TEXT_4 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calamity is man’s true touchstone..
        /// </summary>
        public static string RANDOM_TEXT_5 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me who your friends are and I’ll tell you who you are.
        /// </summary>
        public static string RANDOM_TEXT_6 {
            get {
                return ResourceManager.GetString("RANDOM_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to become a member.
        /// </summary>
        public static string Register_member {
            get {
                return ResourceManager.GetString("Register_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        public static string Resend_Code {
            get {
                return ResourceManager.GetString("Resend_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales statistics.
        /// </summary>
        public static string Sales_Statistics {
            get {
                return ResourceManager.GetString("Sales_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales statistics by day.
        /// </summary>
        public static string Sales_Statistics_by_Day {
            get {
                return ResourceManager.GetString("Sales_Statistics_by_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales statistics by month.
        /// </summary>
        public static string Sales_Statistics_by_Month {
            get {
                return ResourceManager.GetString("Sales_Statistics_by_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Status_Cancel {
            get {
                return ResourceManager.GetString("Status_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Status_New {
            get {
                return ResourceManager.GetString("Status_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string Status_Shipping {
            get {
                return ResourceManager.GetString("Status_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Status_Success {
            get {
                return ResourceManager.GetString("Status_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code sent to your email..
        /// </summary>
        public static string Text_code {
            get {
                return ResourceManager.GetString("Text_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your registered email to retrieve your password..
        /// </summary>
        public static string Text_Forgot_Password {
            get {
                return ResourceManager.GetString("Text_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Text_Here {
            get {
                return ResourceManager.GetString("Text_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login now.
        /// </summary>
        public static string Text_Login_Now {
            get {
                return ResourceManager.GetString("Text_Login_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you already a member?.
        /// </summary>
        public static string Text_Member {
            get {
                return ResourceManager.GetString("Text_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string TEXT_NO_DATA_FOUND {
            get {
                return ResourceManager.GetString("TEXT_NO_DATA_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny access. Contact the administrator for assistance..
        /// </summary>
        public static string TEXT_PAGE_ERROR {
            get {
                return ResourceManager.GetString("TEXT_PAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Tilte_Price {
            get {
                return ResourceManager.GetString("Tilte_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Titile_Comfirm {
            get {
                return ResourceManager.GetString("Titile_Comfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information.
        /// </summary>
        public static string TITLE_ACCOUNT_INFORMATION {
            get {
                return ResourceManager.GetString("TITLE_ACCOUNT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Classification.
        /// </summary>
        public static string Title_Add_Classification {
            get {
                return ResourceManager.GetString("Title_Add_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new employee.
        /// </summary>
        public static string TITLE_ADD_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_ADD_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new stationery.
        /// </summary>
        public static string TITLE_ADD_NEW_STATIONERY {
            get {
                return ResourceManager.GetString("TITLE_ADD_NEW_STATIONERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TITLE_ADDRESS {
            get {
                return ResourceManager.GetString("TITLE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery address.
        /// </summary>
        public static string TITLE_ADDRESS_ORDER {
            get {
                return ResourceManager.GetString("TITLE_ADDRESS_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TITLE_ALL {
            get {
                return ResourceManager.GetString("TITLE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string TITLE_BOOK {
            get {
                return ResourceManager.GetString("TITLE_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string TITLE_BRAND {
            get {
                return ResourceManager.GetString("TITLE_BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Title_cancel {
            get {
                return ResourceManager.GetString("Title_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string TITLE_CART {
            get {
                return ResourceManager.GetString("TITLE_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string TITLE_CHUC_DANH {
            get {
                return ResourceManager.GetString("TITLE_CHUC_DANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product classification.
        /// </summary>
        public static string TITLE_CLASSIFICATION {
            get {
                return ResourceManager.GetString("TITLE_CLASSIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID number.
        /// </summary>
        public static string TITLE_CMND {
            get {
                return ResourceManager.GetString("TITLE_CMND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Title_Code {
            get {
                return ResourceManager.GetString("Title_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string TITLE_COLOR {
            get {
                return ResourceManager.GetString("TITLE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string TITLE_CONFIM_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CONFIM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the order.
        /// </summary>
        public static string Title_Confirm_Order {
            get {
                return ResourceManager.GetString("Title_Confirm_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string TITLE_CONTACT {
            get {
                return ResourceManager.GetString("TITLE_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string TITLE_COUNTRY {
            get {
                return ResourceManager.GetString("TITLE_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new books.
        /// </summary>
        public static string TITLE_CREATE_BOOK {
            get {
                return ResourceManager.GetString("TITLE_CREATE_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string TITLE_CREATE_DATE {
            get {
                return ResourceManager.GetString("TITLE_CREATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stationery.
        /// </summary>
        public static string TITLE_CREATE_STATIONERY {
            get {
                return ResourceManager.GetString("TITLE_CREATE_STATIONERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string TITLE_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found.
        /// </summary>
        public static string TITLE_DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("TITLE_DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string TITLE_DATEOFBIRTH {
            get {
                return ResourceManager.GetString("TITLE_DATEOFBIRTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery charges.
        /// </summary>
        public static string TITLE_DELIVERY_CHARGES {
            get {
                return ResourceManager.GetString("TITLE_DELIVERY_CHARGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        public static string Title_Description_Product {
            get {
                return ResourceManager.GetString("Title_Description_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        public static string Title_Detail_Order {
            get {
                return ResourceManager.GetString("Title_Detail_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TITLE_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string TITLE_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 401.
        /// </summary>
        public static string TITLE_ERROR {
            get {
                return ResourceManager.GetString("TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookstore online.
        /// </summary>
        public static string TITLE_FAHASA {
            get {
                return ResourceManager.GetString("TITLE_FAHASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Title_Forgot_Password {
            get {
                return ResourceManager.GetString("Title_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Support 24/7.
        /// </summary>
        public static string TITLE_FREE_SUPPORT {
            get {
                return ResourceManager.GetString("TITLE_FREE_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Title_From {
            get {
                return ResourceManager.GetString("Title_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookshelf.
        /// </summary>
        public static string TITLE_GIA_SACH {
            get {
                return ResourceManager.GetString("TITLE_GIA_SACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string TITLE_HINH_THUC {
            get {
                return ResourceManager.GetString("TITLE_HINH_THUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string TITLE_HO {
            get {
                return ResourceManager.GetString("TITLE_HO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TITLE_HOME {
            get {
                return ResourceManager.GetString("TITLE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string TITLE_ID {
            get {
                return ResourceManager.GetString("TITLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book code.
        /// </summary>
        public static string TITLE_ID_BOOK {
            get {
                return ResourceManager.GetString("TITLE_ID_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code.
        /// </summary>
        public static string TITLE_ID_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_ID_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string TITLE_IMAGE {
            get {
                return ResourceManager.GetString("TITLE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book information.
        /// </summary>
        public static string TITLE_INFO_BOOK {
            get {
                return ResourceManager.GetString("TITLE_INFO_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string TITLE_INFO_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_INFO_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee information.
        /// </summary>
        public static string TITLE_INFO_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_INFO_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Information.
        /// </summary>
        public static string TITLE_INFO_ORDER {
            get {
                return ResourceManager.GetString("TITLE_INFO_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string TITLE_KICH_THUOC {
            get {
                return ResourceManager.GetString("TITLE_KICH_THUOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string TITLE_LAST_NAME {
            get {
                return ResourceManager.GetString("TITLE_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book List.
        /// </summary>
        public static string TITLE_LIST_BOOK {
            get {
                return ResourceManager.GetString("TITLE_LIST_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List.
        /// </summary>
        public static string TITLE_LIST_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_LIST_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        public static string TITLE_LIST_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_LIST_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string TITLE_LOGOUT {
            get {
                return ResourceManager.GetString("TITLE_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up orders.
        /// </summary>
        public static string Title_Lookup_Order {
            get {
                return ResourceManager.GetString("Title_Lookup_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string TITLE_MATERIAL {
            get {
                return ResourceManager.GetString("TITLE_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no items in your shopping cart..
        /// </summary>
        public static string TITLE_MESSAGE_NO_PRODUCT {
            get {
                return ResourceManager.GetString("TITLE_MESSAGE_NO_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string TITLE_MORE_INFORMATION {
            get {
                return ResourceManager.GetString("TITLE_MORE_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string TITLE_MY_ACCOUNT {
            get {
                return ResourceManager.GetString("TITLE_MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TITLE_NAME {
            get {
                return ResourceManager.GetString("TITLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book name.
        /// </summary>
        public static string TITLE_NAME_BOOK {
            get {
                return ResourceManager.GetString("TITLE_NAME_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name.
        /// </summary>
        public static string TITLE_NAME_EMPLOYEE {
            get {
                return ResourceManager.GetString("TITLE_NAME_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Title_New {
            get {
                return ResourceManager.GetString("Title_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string TITLE_NGON_NGU {
            get {
                return ResourceManager.GetString("TITLE_NGON_NGU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Title_Nha_Cung_Cap {
            get {
                return ResourceManager.GetString("Title_Nha_Cung_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing company.
        /// </summary>
        public static string TITLE_NHA_XUAT_BAN {
            get {
                return ResourceManager.GetString("TITLE_NHA_XUAT_BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Title_Notification {
            get {
                return ResourceManager.GetString("Title_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original price.
        /// </summary>
        public static string Title_Original_Price {
            get {
                return ResourceManager.GetString("Title_Original_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string TITLE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức thanh toán.
        /// </summary>
        public static string Title_Payments {
            get {
                return ResourceManager.GetString("Title_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal infor.
        /// </summary>
        public static string Title_Personal_info {
            get {
                return ResourceManager.GetString("Title_Personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify.
        /// </summary>
        public static string TITLE_PHAN_LOAI {
            get {
                return ResourceManager.GetString("TITLE_PHAN_LOAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19/5000
        ///Access Permission.
        /// </summary>
        public static string TITLE_PHAN_QUYEN {
            get {
                return ResourceManager.GetString("TITLE_PHAN_QUYEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string TITLE_PHONE {
            get {
                return ResourceManager.GetString("TITLE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wards.
        /// </summary>
        public static string TITLE_PHUONG {
            get {
                return ResourceManager.GetString("TITLE_PHUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string TITLE_PRICE {
            get {
                return ResourceManager.GetString("TITLE_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Order.
        /// </summary>
        public static string Title_Process_Order {
            get {
                return ResourceManager.GetString("Title_Process_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string TITLE_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("TITLE_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Title_Provider {
            get {
                return ResourceManager.GetString("Title_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional.
        /// </summary>
        public static string TITLE_PROVISIONAL {
            get {
                return ResourceManager.GetString("TITLE_PROVISIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string TITLE_QUAN {
            get {
                return ResourceManager.GetString("TITLE_QUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string TITLE_QUANTITY {
            get {
                return ResourceManager.GetString("TITLE_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string TITLE_QUOC_GIA {
            get {
                return ResourceManager.GetString("TITLE_QUOC_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14/5000
        ///Access rights.
        /// </summary>
        public static string TITLE_QUYEN_TRUY_CAP {
            get {
                return ResourceManager.GetString("TITLE_QUYEN_TRUY_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string TITLE_REGISTER {
            get {
                return ResourceManager.GetString("TITLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Title_Revenue {
            get {
                return ResourceManager.GetString("Title_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Title_Sale {
            get {
                return ResourceManager.GetString("Title_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale product.
        /// </summary>
        public static string Title_Sale_Product {
            get {
                return ResourceManager.GetString("Title_Sale_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Title_Saving {
            get {
                return ResourceManager.GetString("Title_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search orders.
        /// </summary>
        public static string Title_Search_Orders {
            get {
                return ResourceManager.GetString("Title_Search_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        public static string TITLE_SEE_ALL {
            get {
                return ResourceManager.GetString("TITLE_SEE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue shopping.
        /// </summary>
        public static string TITLE_SHOPPING {
            get {
                return ResourceManager.GetString("TITLE_SHOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages.
        /// </summary>
        public static string TITLE_SO_TRANG {
            get {
                return ResourceManager.GetString("TITLE_SO_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationerry.
        /// </summary>
        public static string TITLE_STATIONERY {
            get {
                return ResourceManager.GetString("TITLE_STATIONERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of stationery.
        /// </summary>
        public static string TITLE_STATIONERY_LIST {
            get {
                return ResourceManager.GetString("TITLE_STATIONERY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics orders by day.
        /// </summary>
        public static string Title_Statistic_Order_By_Day {
            get {
                return ResourceManager.GetString("Title_Statistic_Order_By_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics orders by month.
        /// </summary>
        public static string Title_Statistic_Order_By_Month {
            get {
                return ResourceManager.GetString("Title_Statistic_Order_By_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Title_Statistics {
            get {
                return ResourceManager.GetString("Title_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics orders.
        /// </summary>
        public static string Title_Statistics_Orders {
            get {
                return ResourceManager.GetString("Title_Statistics_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TITLE_STATUS {
            get {
                return ResourceManager.GetString("TITLE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed.
        /// </summary>
        public static string Title_Succeed {
            get {
                return ResourceManager.GetString("Title_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string TITLE_SUPPORT {
            get {
                return ResourceManager.GetString("TITLE_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Title_Surname {
            get {
                return ResourceManager.GetString("Title_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TITLE_TEN {
            get {
                return ResourceManager.GetString("TITLE_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province / City.
        /// </summary>
        public static string TITLE_THANH_PHO {
            get {
                return ResourceManager.GetString("TITLE_THANH_PHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Title_To {
            get {
                return ResourceManager.GetString("Title_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string TITLE_TOM_TAC {
            get {
                return ResourceManager.GetString("TITLE_TOM_TAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TITLE_TOTAL {
            get {
                return ResourceManager.GetString("TITLE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11/5000
        ///Weight.
        /// </summary>
        public static string TITLE_TRONG_LUONG {
            get {
                return ResourceManager.GetString("TITLE_TRONG_LUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update order information.
        /// </summary>
        public static string TITLE_UPDATE_INFO_CUSTOMER {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_INFO_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string TITLE_USERNAME {
            get {
                return ResourceManager.GetString("TITLE_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string TITLE_VIEW {
            get {
                return ResourceManager.GetString("TITLE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Statistics.
        /// </summary>
        public static string Tittle_Product_Statistics {
            get {
                return ResourceManager.GetString("Tittle_Product_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string TITTLE_TAC_GIA {
            get {
                return ResourceManager.GetString("TITTLE_TAC_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string TXT_CHOOSE_STATUS {
            get {
                return ResourceManager.GetString("TXT_CHOOSE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        public static string Update_Failed {
            get {
                return ResourceManager.GetString("Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₫.
        /// </summary>
        public static string VND {
            get {
                return ResourceManager.GetString("VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the FAHASA Family.
        /// </summary>
        public static string WELCOME_FAHASA {
            get {
                return ResourceManager.GetString("WELCOME_FAHASA", resourceCulture);
            }
        }
    }
}
